language: node_js

node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - node

matrix:
  # Report status as soon as just the required tests run
  fast_finish: true
  allow_failures:
    # We do not support < 10 or > 14, but we can still test it
    - node_js: node
