language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - node

matrix:
  # Report status as soon as just the required tests run
  fast_finish: true
  allow_failures:
    # We do not support < 8 or > 10, but we can still test it
    - node_js: "6"
    - node_js: "7"
    - node_js: "11"
    - node_js: "12"
    - node_js: "13"
    - node_js: "14"
    - node_js: node
